### ISSUE TITLE
`output-stack` in ProducesManyOfTypeInstruction

### ISSUE THREAD

**Issue by thelmuth** [push-language/Puj#6]
This line seems to assume `output-stack` is a single stack:

https://github.com/push-language/Puj/blob/473a1cdc58404858baa0da90e5a2882694c68b32/src/puj/push/unit.clj#L107

But, as far as I know, `push-to-stacks` only works with a collection of stacks, which would not be the case here:

https://github.com/push-language/Puj/blob/473a1cdc58404858baa0da90e5a2882694c68b32/src/puj/push/unit.clj#L128

So, which is it, and should there be a test that catches this? Or am I misunderstanding something?

**Comment by thelmuth** [comment]
I'm asking in relation to #3, which could make this take either one, but I wanted to make sure I knew what was intended first.

**Comment by erp12** [comment]
The intended (but currently undocumented, as you pointed out) semantics of a `ProducesManyOfTypeInstruction` is to produce an unknown number of values for a single type.
For example: `{type}_dup_times`,`str_split_on_char`, `chars_from_str`

Even with the changes to `SimpleInstruction` you made this kind of instruction will still be difficult to express, unless I am overlooking something. 

I can't think of a situation where `ProducesManyOfTypeInstruction` would be producing more than one type.

**Comment by lspector** [comment]
> I can't think of a situation where ProducesManyOfTypeInstruction would be producing more than one type.

I haven't fully followed this so I'm not sure if it's relevant, but I can certainly imagine instructions that push multiple values of multiple types. Will we actually want anything like this? I don't know. But an arbitrary one just off the top of my head is an instruction that takes a vector of integers and pushes each of the integers and also `true` or `false` on the `:boolean` stack for each, indicating whether or not it is positive. Weird, yeah, but I'm not convinced something like that wouldn't be desirable in some situation.

**Comment by thelmuth** [comment]
> The intended (but currently undocumented, as you pointed out) semantics of a `ProducesManyOfTypeInstruction` is to produce an unknown number of values for a single type.
> For example: `{type}_dup_times`,`str_split_on_char`, `chars_from_str`
> 
> Even with the changes to `SimpleInstruction` you made this kind of instruction will still be difficult to express, unless I am overlooking something.
> 
> I can't think of a situation where `ProducesManyOfTypeInstruction` would be producing more than one type.

Ok, great. I think I misread the call to `push-to-stacks` to only take a single `output-stack`, but now I see you are repeating it, which means the second argument will be a collection (which it needs to be).

> I haven't fully followed this so I'm not sure if it's relevant, but I can certainly imagine instructions that push multiple values of multiple types. Will we actually want anything like this? I don't know. But an arbitrary one just off the top of my head is an instruction that takes a vector of integers and pushes each of the integers and also `true` or `false` on the `:boolean` stack for each, indicating whether or not it is positive. Weird, yeah, but I'm not convinced something like that wouldn't be desirable in some situation.

Eddie has defined a few different instruction-defining `defrecords`, some for specific types of instructions, but one that allows for any Push state -> Push state function to define an instruction. So, we could define an instruction like the one you describe there.
