### ISSUE TITLE
Change state to pushstate

### ISSUE THREAD

**Issue by thelmuth** [push-language/Puj#7]
See: https://push-language.hampshire.edu/t/puj-implementation-discussion/1432?u=thelmuth

**Comment by erp12** [comment]
I will take care of this shortly.

**Comment by julian-zucker** [comment]
That link is not publicly available, and I don't see how I can create an account on the Push language discourse site, which is unfortunate. I completely understand if you want to keep some discussion private, and continue using that tool, which looks like it has a long history! As someone's who's trying to follow this repo, I'd appreciate if you could move some discussions to gitter or at least copy the body text over? I want to contribute some code or docs to this project, but that's difficult if I can't read the github issues.

**Comment by erp12** [comment]
@julian-zucker makes a good point. Our discourse conversations are long, scattered, and usually half-thought through. We should probably be at least writing a TL;DR for each Github issue/PR that stems from a conversation over there. For the sanity of those inside and outside the lab 😆 

Here is the summary of the thread which inspired this issue:

> “state” is being used in at least 2 different contexts here, for the namespace of Push states and the push state itself. As far as I know, Clojure will know which one you mean in the right places, but this is dangerous reuse. We have been burned before by using “state” to mean different things.
>
> At minimum, let's change the namespace to `puj.push.pushstate`, as well as the require to `pushstate`.

**Comment by lspector** [comment]
Agreed. Assuming that we do want external contributors, which I hadn't really thought about previously, then it does make sense to have Puj-specific discussions on github.

**Comment by erp12** [comment]
If we have a public open source repository it will kind of imply the existence of external contributors (opening issues, starting pull requests, and forking) unless we put in work discourage that stuff. I wouldn't recommend the closed off approach, but some projects succeed under that model (such as the Clojure language :disappointed: )

I wouldn't expect us to have external collaborators/maintainers (making commits, merging pull requests, cutting releases). Basically the difference is the authority to actualize code changes.

**Comment by thelmuth** [comment]
I'm happy to have external contributors. That said, I'm sure some of the discussion would happen on the Push Discourse, since that's the best place to talk about Push. I think we should do our best to make public-facing things like issues clear without being in on the Discourse discussions.
